# Generated by Django 4.1.3 on 2022-11-27 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('bio', models.TextField(blank=True, max_length=200, null=True, verbose_name='Bio')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic', verbose_name='Profile Picture')),
                ('_base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='pulsifi.profile')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('visible', models.BooleanField(default=True, verbose_name='Visibility')),
                ('_likes', models.PositiveIntegerField(default=0, verbose_name='Number of Likes')),
                ('_dislikes', models.PositiveIntegerField(default=0, verbose_name='Number of Dislikes')),
                ('_date_time_created', models.DateTimeField(auto_now=True, verbose_name='Creation Date & Time')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsifi.profile', verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Pulse',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('pulse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulsifi.pulse')),
                ('_object_id', models.PositiveIntegerField()),
                ('_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Reply',
            },
            bases=('pulsifi.pulse',),
        ),
    ]
