# Generated by Django 4.1.4 on 2022-12-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pulse',
            name='unlisted',
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PR', 'In progress'), ('RE', 'Rejected'), ('CN', 'Confirmed')], max_length=2, verbose_name='Status'),
        ),
    ]
