# Generated by Django 4.1.3 on 2022-11-26 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pulsifi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='post',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visibility'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='pulsifi.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='_date_time_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Creation Date & Time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic', verbose_name='Profile Picture'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pulsifi.post')),
                ('_object_id', models.PositiveIntegerField()),
                ('_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Reply',
            },
            bases=('pulsifi.post',),
        ),
    ]
