# Generated by Django 4.1.4 on 2022-12-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0002_remove_profile_name_remove_pulse_unlisted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]