# Generated by Django 4.1.3 on 2022-11-26 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0002_rename_user_post_creator_post_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pulsifi.profile', verbose_name='Creator'),
        ),
    ]
