# Generated by Django 4.1.5 on 2023-01-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0002_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report'},
        ),
    ]
