# Generated by Django 4.1.4 on 2022-12-21 22:42

import django.db.models.deletion
from django.db import migrations, models

import pulsifi.models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0003_remove_pulse__dislikes_remove_pulse__likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_staff',
            field=models.ForeignKey(default=pulsifi.models._choose_default_assigned_staff, limit_choices_to={'_base_user__is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to='pulsifi.profile', verbose_name='Assigned Staff Member'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pulsifi.profile', verbose_name='Reporter'),
        ),
    ]
