# Generated by Django 4.1.5 on 2023-01-06 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import pulsifi.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0003_alter_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assigned_staff',
            field=models.ForeignKey(default=pulsifi.models.utils.get_random_moderator_id, limit_choices_to={'groups__name': 'Moderators'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Staff Member'),
        ),
    ]
