# Generated by Django 4.1.4 on 2022-12-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0006_alter_report_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Reply', 'verbose_name_plural': 'Replies'},
        ),
    ]
