# Generated by Django 4.1.5 on 2023-01-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pulsifi', '0006_remove_report_assigned_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='_content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'pulsifi', 'model__in': ['user', 'pulse', 'reply']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='reply',
            index=models.Index(fields=['_content_type', '_object_id'], name='pulsifi_rep__conten_eaffc4_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['_content_type', '_object_id'], name='pulsifi_rep__conten_e403cf_idx'),
        ),
    ]
