# Generated by Django 4.1.4 on 2022-12-23 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0007_alter_reply_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='visible',
        ),
    ]
