# Generated by Django 4.1.5 on 2023-01-13 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pulsifi', '0007_alter_report__content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='_content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'pulsifi', 'model__in': ('pulse', 'reply')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Replied Content Type'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='_object_id',
            field=models.PositiveIntegerField(verbose_name='Replied Content ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='_content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'pulsifi', 'model__in': ('user', 'pulse', 'reply')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Reported Object Type'),
        ),
        migrations.AlterField(
            model_name='report',
            name='_object_id',
            field=models.PositiveIntegerField(verbose_name='Reported Object ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user is visible. Unselect this instead of deleting accounts.', verbose_name='Is visible?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Is a staff member?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='Is a superuser?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Is verified?'),
        ),
    ]
