# Generated by Django 4.1.5 on 2023-01-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0008_alter_reply__content_type_alter_reply__object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulse',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Is visible?'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Is visible?'),
        ),
    ]
