# Generated by Django 4.1.5 on 2023-01-13 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0009_alter_pulse_visible_alter_reply_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='_original_pulse',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pulsifi.pulse', verbose_name='Original Pulse'),
        ),
    ]
