# Generated by Django 4.1.5 on 2023-01-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0010_alter_reply__original_pulse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='_original_pulse',
        ),
    ]
