# Generated by Django 4.1.5 on 2023-01-15 03:22

from django.db import migrations, models

import pulsifi.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0011_remove_reply__original_pulse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'That Email Address is already in use by another user.'}, max_length=254, unique=True, validators=[pulsifi.validators.HTML5EmailValidator, pulsifi.validators.validate_free_email, pulsifi.validators.validate_confusables_email, pulsifi.validators.validate_tld_email, pulsifi.validators.validate_example_email], verbose_name='email address'),
        ),
    ]
