# Generated by Django 4.1.5 on 2023-01-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0012_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Bio'),
            preserve_default=False,
        ),
    ]
