# Generated by Django 4.1.5 on 2023-01-16 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import pulsifi.models_utils


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0013_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='assigned_staff_member',
            field=models.ForeignKey(default=pulsifi.models_utils.get_random_staff_member, limit_choices_to={'groups__name': 'Moderators', 'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='staff_assigned_report_set', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Staff Member'),
        ),
    ]
