# Generated by Django 4.1.6 on 2023-02-05 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import pulsifi.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0015_alter_user_date_joined_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='assigned_staff_member',
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_moderator',
            field=models.ForeignKey(default=pulsifi.models.utils.get_random_moderator_id, limit_choices_to={'groups__name': 'Moderators', 'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='moderator_assigned_report_set', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Moderator'),
        ),
    ]
