# Generated by Django 4.1.6 on 2023-02-06 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pulsifi', '0016_remove_report_assigned_staff_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='_content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'pulsifi', 'model__in': ['user', 'pulse', 'reply']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Reported Object Type'),
        ),
    ]
