# Generated by Django 4.1.6 on 2023-02-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulsifi', '0017_alter_report__content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='Is a staff member?'),
        ),
    ]
